Repository iiiiii-dle/TheMore, pull requests merged in 2024-03, with the labels that each got.

#1 feat: 패키지 구조 설정 및 라이브러리 설정
  TheMore_be/.classpath
  TheMore_be/.gitignore
  TheMore_be/.project
  TheMore_be/.settings/org.eclipse.core.resources.prefs
  TheMore_be/.settings/org.eclipse.jdt.core.prefs
  TheMore_be/src/DAO/BudgetDAO.java
  TheMore_be/src/DAO/CategoryDAO.java
  TheMore_be/src/DAO/ExpensesDAO.java
  TheMore_be/src/DAO/UsersDAO.java
  TheMore_be/src/DB/DBConnection.java
  TheMore_be/src/DTO/Budget.java
  TheMore_be/src/DTO/Category.java
  TheMore_be/src/DTO/Expenses.java
  TheMore_be/src/DTO/Users.java
  TheMore_be/src/server/ChatServer.java
  TheMore_be/src/server/Sever.java
Labels: good first issue, feat, server

#2 feat/header_code 프론트 추가
  frontend/component/account.html
  frontend/component/statistics.html
  frontend/html/account.html
  frontend/html/statistics.html
  frontend/images/4960188.png
  frontend/images/Calendar.png
  frontend/images/Sign_in_squre.png
  frontend/images/Trending-up.png
  frontend/images/user_3059416.png
  frontend/style/header.css
  frontend/style/header_ac.css
  frontend/style/header_st.css
Labels: feat, client

#3 feat: quote 랜덤 명언 생성기
  frontend/html/quote.html
  frontend/js/quote.js
  frontend/style/quote.css
Labels: feat, client

#5 fix: gitignore 삭제 및 프로젝트명 backend로 변경
  TheMore_be/.gitignore
  TheMore_be/.project
Labels: server, fix

#6 fix: 폰트 css 분리
  frontend/style/nomalize.css
  frontend/style/quote.css
Labels: client, fix

#7 feat/달력 코드 작성
  frontend/html/acountBook.html
  frontend/js/calendar.js
  frontend/style/calendar.css
Labels: feat, client

#8 logIn과 membership 페이지
  frontend/html/logIn.html
  frontend/html/membership.html
  frontend/images/3babypig.png
  frontend/images/backgroundColor.png
  frontend/images/warning.png
Labels: feat, client

#9 fix: header 수정 및 가계부 부분 코드 수정
  frontend/component/header.html
  frontend/html/account.html
  frontend/html/acountBook.html
  frontend/style/account.css
  frontend/style/calendar.css
Labels: client, fix

#11 fix: account.html 파일에 넣을 js 파일 통폐합 및 명언/수입지출창 수정
  frontend/html/account.html
  frontend/js/account.js
  frontend/js/quote.js
  frontend/style/account.css
  frontend/style/expenseBox.css
Labels: client, fix

#12 Fe/feat/statistics 월 선택, 수입/지출 선택
  frontend/html/month.html
  frontend/html/st_expend.html
  frontend/html/st_income.html
  frontend/html/statistics.html
  frontend/js/month.js
  frontend/style/month.css
  frontend/style/st_expend.css
  frontend/style/st_income.css
  frontend/style/statistics.css
Labels: feat, client

#13 myPage.html 생성 및 modify.html 생성 - 내 정보, 내 정보 수정
  frontend/html/modify.html
  frontend/html/myPage.html
Labels: feat, client

#14 feat/main-page 로그인 전 메인페이지 nav section 작성
  frontend/html/index.html
  frontend/images/before_login_background.png
  frontend/images/netbook 1.png
  frontend/style/main.css
Labels: feat, client

#16 fix: 수입 지출 박스 내 요소 추가
  frontend/html/account.html
  frontend/images/Pluse.png
  frontend/style/expenseBox.css
Labels: client, fix

#17 fix: 수입 지출 버튼 클릭 시 효과 수정 + 필요 없는 파일 삭제
  frontend/html/account.html
  frontend/html/expensesBox.html
  frontend/html/quote.html
  frontend/js/account.js
  frontend/style/expenseBox.css
Labels: client, fix

#18 css 분할
  frontend/html/logIn.html
  frontend/html/membership.html
  frontend/html/modify.html
  frontend/html/myPage.html
  frontend/style/logIn.css
  frontend/style/membership.css
  frontend/style/modify.css
  frontend/style/myPage.css
Labels: client, fix

#19 로그인 전 메인페이지- 2번째 구역 진행중, 배경 이미지 위치 변경,핸드폰 이미지 추가
  frontend/html/index.html
  frontend/images/brfore_login_img.png
  frontend/images/iPhone 1.png
  frontend/style/main.css
Labels: feat, client

#24 feat: 프로젝트 구조 및 buildpath, DTO 파일 작성
  backend/.classpath
  backend/.project
  backend/src/DAO/BudgetDAO.java
  backend/src/DAO/CategoryDAO.java
  backend/src/DAO/ExpensesDAO.java
  backend/src/DAO/UsersDAO.java
  backend/src/DB/DBConnection.java
  backend/src/DTO/Budget.java
  backend/src/DTO/Category.java
  backend/src/DTO/Expenses.java
  backend/src/DTO/Users.java
  backend/src/server/ChatServer.java
  backend/src/server/Sever.java
Labels: feat, server

#26 로그인전메인페이지 css적용전 폼완성
  frontend/html/index.html
  frontend/images/beforeMainPage/45999 1.png
  frontend/images/beforeMainPage/Brush.png
  frontend/images/beforeMainPage/Calendar.png
  frontend/images/beforeMainPage/Chat-1.png
  frontend/images/beforeMainPage/Copy-Document.png
  frontend/images/beforeMainPage/Ellipse size-151.png
  frontend/images/beforeMainPage/Ellipse size-5.png
  frontend/images/beforeMainPage/Trending-up.png
  frontend/images/beforeMainPage/Two-Person.png
  frontend/images/beforeMainPage/before_login_background.png
  frontend/images/beforeMainPage/brfore_login_img.png
  frontend/images/beforeMainPage/iPhone 1.png
  frontend/images/beforeMainPage/netbook 1.png
  frontend/images/beforeMainPage/로그아웃.png
  frontend/style/main.css
Labels: client

#27 feat: DAO에 클래스에 insert, delete, update, list 조회 메소드 작성
  backend/.classpath
  backend/src/DAO/ExpensesDAO.java
  backend/src/DTO/Expenses.java
Labels: feat, server

#30 fix: 수입지출DAO 에러 수정
  backend/src/DAO/ExpensesDAO.java
Labels: 🪳🪲🐞bug, server, fix

#32 회원가입 페이지와 연동하는 server 작업
  backend/src/server/Sever.java
Labels: feat, server

#33 membership.js forData함수 수정
  frontend/html/membership.html
  frontend/js/membership.js
Labels: client, fix

#35 server와 통신하는 logIn.js 생성 및 html 수정
  frontend/html/logIn.html
  frontend/js/logIn.js
Labels: 💡feat, 🖥️client

#36 UsersDAO 작업
  backend/src/DAO/UsersDAO.java
Labels: 💡feat, 💾server

#38 창 조절시 그래프 겹치는 현상 수정
  frontend/style/grape.css
Labels: 🖥️client, ✒️fix

#39 BudgetDAO DTO 예산 저장, 삭제, 수정, 조회 기능 추가
  backend/src/DAO/BudgetDAO.java
  backend/src/DTO/Budget.java
Labels: 💡feat, 💾server

#40 로그인 전 메인페이지 추가 작업 사항
  frontend/html/account.html
  frontend/html/index.html
  frontend/images/beforeMainPage/45999 1.png
  frontend/images/beforeMainPage/Copy-Document.png
  frontend/images/beforeMainPage/Ellipse_size_151.png
  frontend/images/beforeMainPage/Ellipse_size_5.png
  frontend/images/beforeMainPage/bg_point1.png
  frontend/images/beforeMainPage/bg_point1_on.png
  frontend/images/beforeMainPage/bg_point2.png
  frontend/images/beforeMainPage/bg_point2_on.png
  frontend/images/beforeMainPage/bg_point3.png
  frontend/images/beforeMainPage/bg_point3_on.png
  frontend/images/beforeMainPage/bg_point4.png
  frontend/images/beforeMainPage/bg_point4_on.png
  frontend/images/beforeMainPage/bg_point5.png
  frontend/images/beforeMainPage/bg_point5_on.png
  frontend/images/beforeMainPage/bg_point6.png
  frontend/images/beforeMainPage/bg_point6_on.png
  frontend/images/beforeMainPage/iPhone1.png
  frontend/images/beforeMainPage/macbook.png
  frontend/images/beforeMainPage/netbook1.png
  frontend/js/main.js
  frontend/style/expenseBox.css
  frontend/style/main.css
Labels: 🖥️client, ✒️fix

#41 클라이언트에 채팅 서버 연결 및 상대방 채팅 데이터 처리
  frontend/js/chat_log.js
  frontend/js/socket/chatSocket.js
  frontend/js/socket/messageHandler.js
Labels: 💡feat, 🖥️client

#44 채팅 서버 임시 생성
  backend/src/server/ChatServer.java
Labels: 💡feat, 💾server

#43 예산 / 수입 / 지출 추가 화면, 프로그레스바 생성
  frontend/html/account.html
  frontend/js/account.js
  frontend/style/account.css
  frontend/style/calendar.css
  frontend/style/expenseBox.css
  frontend/style/nomalize.css
Labels: 🖥️client, ✒️fix

#45 modify.js 추가 및 memebership, modify, myPage 에 정보 공개 name="isHidden"으로 수정
  frontend/html/membership.html
  frontend/html/modify.html
  frontend/html/myPage.html
  frontend/js/modify.js
  frontend/js/myPage.js
Labels: 💡feat, 🖥️client

#48 백엔드 유저 계정 비활성화 구현
  backend/src/DAO/UsersDAO.java
Labels: 💡feat, 💾server

#47 버그 fix: account.html, expenseAdd.css, acount.js 수정
  frontend/html/account.html
  frontend/js/account.js
Labels: 🖥️client, ✒️fix

#49 UsersDAO 주석 수정 및 필요 없는 데이터 삭제
  backend/src/DAO/UsersDAO.java
Labels: 💾server, ✒️fix

#50 feat: account2.js 파일 추가(account.js 파일 class화)
  frontend/js/account2.js
Labels: 💡feat, 🖥️client

#51 채팅창 경계 둥글게 수정 및 placeholder 간격 조정
  frontend/style/chat_log.css
Labels: 🖥️client, ✒️fix

#52 fix: account 오류 수정 중
  frontend/html/account.html
  frontend/js/account2.js
Labels: 🖥️client, ✒️fix

#54 fix: DBConnection에서 openConnection을 private으로, getConnection을 public으로
  backend/src/DB/DBConnection.java
Labels: 💾server, ✒️fix

#55 예산 날짜 월과 userId 입력시 monney 조회 기능 수정
  backend/src/DAO/BudgetDAO.java
  backend/src/DTO/Budget.java
Labels: 💾server, ✒️fix

#56 지출과 수입 값을 가져와서 지출이면 지출의 합, 수입이면 수입의 합, 을 출력
  backend/src/DAO/ExpensesDAO.java
Labels: 💡feat, 💾server

#57 회원가입 alert 최종 수정
  frontend/html/membership.html
  frontend/js/membership.js
Labels: 💡feat, 🖥️client, ✒️fix

#58 feat: socket.js 생성
  frontend/js/socket/socket.js
Labels: 🖥️client, ✒️fix

#62 지출 출력 하기위해 수정
  frontend/html/statistics.html
  frontend/js/statisticsServer.js
  frontend/style/mark_expend.css
Labels: 💡feat, 🖥️client, ✒️fix

#63 expenseAdd js class 화
  frontend/js/account2.js
Labels: 🖥️client, ✒️fix

#64 Chat_log.js 파일 Message Data SessionStorage에서 획득하여 전송
  frontend/js/chat_log.js
Labels: 🖥️client, ✒️fix

#66 fix: package 이름 소문자로 변경
  backend/src/server/Sever.java
  backend/src/service/LoginService.java
Labels: 💾server, ✒️fix

#71 비로그인_메인페이지_수정사항(위로가기, 이미지교체, 오타수정)
  frontend/html/index.html
  frontend/images/beforeMainPage/arrow.png
  frontend/images/beforeMainPage/before_login_background.png
  frontend/images/beforeMainPage/circle.png
  frontend/images/beforeMainPage/circle2.png
  frontend/images/beforeMainPage/circle3.png
  frontend/images/beforeMainPage/circle4.png
  frontend/images/beforeMainPage/circle5.png
  frontend/images/beforeMainPage/circle6.png
  frontend/images/beforeMainPage/iPhone.png
  frontend/images/beforeMainPage/iPhone1.png
  frontend/images/beforeMainPage/macbook.png
  frontend/images/beforeMainPage/netbook.png
  frontend/images/beforeMainPage/netbook_bule.png
  frontend/images/beforeMainPage/netbook_green.png
  frontend/images/beforeMainPage/netbook_pink.png
  frontend/images/before_login_background.png
  frontend/images/brfore_login_img.png
  frontend/images/iPhone 1.png
  frontend/images/netbook 1.png
  frontend/js/main.js
  frontend/js/socket/loginSocket.js
  frontend/style/main.css
Labels: ❎remove, 🔀merge, 💡feat, 🖥️client, ✒️fix

#72 UserDAO, LoginService, Server 수정
  backend/src/DAO/UsersDAO.java
  backend/src/server/ChatServer.java
  backend/src/server/Sever.java
  backend/src/service/LoginService.java
Labels: 💾server, ✒️fix

#73 fix rename setting
  frontend/html/logIn.html
  frontend/js/chat_log.js
  frontend/js/logIn.js
Labels: 🖥️client, ✒️fix

#74 logIn Swal 창 구현
  frontend/html/logIn.html
  frontend/js/logIn.js
Labels: 🖥️client, ✒️fix

#75 데이터베이스에서 입력된 값을 json화 시켜서 서버에 전달
  backend/src/DAO/ExpensesDAO.java
Labels: 💡feat, 💾server, ✒️fix

#77 테마 색상 변경
  frontend/html/account.html
  frontend/js/account.js
  frontend/js/account2.js
  frontend/style/account.css
  frontend/style/expenseBox.css
Labels: 💡feat, 🖥️client

#78 logIn 기능 프론트 완성(진)
  frontend/html/logIn.html
  frontend/js/chat_log.js
  frontend/js/logIn.js
  frontend/js/socket/loginSocket.js
Labels: 💡feat, 🖥️client

#79 비밀번호 확인 기능 구현
  frontend/html/membership.html
  frontend/js/membership.js
  frontend/style/membership.css
Labels: 🖥️client, ✒️fix

#80 backend login 완성(진)
  backend/src/DB/DBConnection.java
  backend/src/server/Sever.java
  backend/src/service/LoginService.java
Labels: 💾server, ✒️fix

#81 fix: String을 Date로 파싱, 잘못된 메서드 수정
  backend/src/service/ExpensesServiceImpl.java
Labels: 💾server, ✒️fix

#82 gitignore jar 적용 & classpath와 project 파일 제외 적용
  .gitignore
  backend/lib/Java-WebSocket-1.5.6.jar
  backend/lib/json-20240303.jar
  backend/lib/mysql-connector-j-8.0.33.jar
  backend/lib/slf4j-api-2.0.12.jar
Labels: 📄docs, 💡feat, 💾server, ✒️fix

#83 fix: 코드 스타일 수정. 메소드 매개변수 추가
  backend/src/server/Sever.java
  backend/src/service/ExpensesService.java
  backend/src/service/ExpensesServiceImpl.java
Labels: 💾server, ✒️fix

#85 logIn 디자인 수정 및 account.html로 넘어가는 기능 추가
  .vscode/settings.json
  frontend/html/logIn.html
  frontend/js/logIn.js
  frontend/style/logIn.css
Labels: 🖥️client, ✒️fix

#86 membership hover 수정 및 회원가입 시 값 입력 유도 함수 추가
  frontend/js/membership.js
  frontend/style/membership.css
Labels: 🖥️client, ✒️fix

#88 fix&feat: 서버쪽 코드 수정 및 parse 메소드 추가
  backend/src/server/Sever.java
  backend/src/service/ExpensesService.java
  backend/src/service/ExpensesServiceImpl.java
Labels: 💡feat, 💾server, ✒️fix

#90 UserService 수정 조회 기능 추가
  backend/src/server/Sever.java
  backend/src/service/UserService.java
  backend/src/service/UserServiceImpl.java
Labels: 💡feat, 💾server

#87 내 정보에서 button 클릭 시 수정 화면으로 이동
  frontend/html/myPage.html
  frontend/js/myPage.js
  frontend/style/myPage.css
Labels: 🖥️client, ✒️fix

#92 account page css 수정
  frontend/html/account.html
  frontend/js/account2.js
  frontend/style/calendar.css
  frontend/style/expenseBox.css
Labels: 🖥️client, ✒️fix

#93 fix: 중괄호 삭제
  backend/src/server/Sever.java
Labels: 🪳🪲🐞bug, 💾server

#95 fix: ExpensesServiceImpl 클래스의 parse Method 수정
  backend/src/service/ExpensesServiceImpl.java
Labels: 💾server, ✒️fix

#97 Fix/get expenses list fixed
  backend/src/DTO/Expenses.java
  backend/src/service/ExpensesServiceImpl.java
Labels: 💾server, ✒️fix

#98 회원 정보 수정 페이지에서 json 데이터 작성
  frontend/html/modify.html
  frontend/js/modify.js
  frontend/style/modify.css
Labels: 🖥️client, ✒️fix

#99 전체 지출 출력 웹 소켓 연결
  frontend/html/incometotal.html
  frontend/js/incomeserver.js
Labels: 💡feat, 🖥️client

#100 내 가계부 페이지 기능 수정
  frontend/html/account.html
  frontend/js/account.js
Labels: 🖥️client, ✒️fix

#101 오류 수정
  backend/src/DAO/ExpensesDAO.java
  backend/src/service/ExpensesServiceImpl.java
Labels: 💾server, ✒️fix

#102 account.js error 수정
  frontend/js/account.js
Labels: 🖥️client, ✒️fix

#103 login 기능 최종
  frontend/js/logIn.js
Labels: 🖥️client, ✒️fix

#104 DAO filter == true 구분
  backend/src/DAO/ExpensesDAO.java
  backend/src/DTO/Expenses.java
Labels: 💾server, ✒️fix

#105 Fe/fix/socket server
  frontend/js/incomeserver.js
  frontend/js/socket/stacSocket.js
Labels: 💾server, ✒️fix

#107 회원 가입 기능 백엔드 수정 및 기능 추가
  backend/src/DAO/UsersDAO.java
  backend/src/DTO/Users.java
  backend/src/service/UserService.java
  backend/src/service/UserServiceImpl.java
Labels: 💡feat, 💾server, ✒️fix

#108 fix: account.html 수정
  frontend/html/account.html
Labels: 🖥️client, ✒️fix

#111 토탈 출력 성공
  frontend/html/statistics.html
  frontend/js/incomeserver.js
Labels: 💡feat, 🖥️client, ✒️fix

#112 지출 수입 통계 카테고리별 지출합 수입합 통계 수정
  backend/src/DAO/ExpensesDAO.java
Labels: 💡feat, 💾server, ✒️fix

#113 Update User 이벤트 오류 수정
  backend/src/DAO/UsersDAO.java
  backend/src/service/UserServiceImpl.java
Labels: 💾server, ✒️fix

#117 내 정보, 내 정보 수정 최종
  frontend/html/myPage.html
  frontend/js/modify.js
  frontend/js/myPage.js
Labels: 🖥️client, ✒️fix

#118 fix: ExpensesServiceImpl 불필요한 코드 수정 및 삭제
  backend/src/service/ExpensesServiceImpl.java
Labels: 💾server, ✒️fix

#119 feat: Expenses 클래스에 toString override
  backend/src/DTO/Expenses.java
Labels: 💡feat, 💾server

#120 지출 통계
  frontend/html/st_grape_expend.html
  frontend/html/statistics.html
  frontend/html/statistics_income.html
  frontend/js/doughnutGrap.js
  frontend/js/incomeserver.js
  frontend/js/month.js
Labels: 🖥️client, ✒️fix

#121 header 수정
  frontend/html/logIn.html
  frontend/html/membership.html
  frontend/html/modify.html
  frontend/html/myPage.html
Labels: 🖥️client, ✒️fix

#122 카테고리 별 지출, 수입을 출력
  backend/src/DAO/ExpensesDAO.java
  backend/src/DTO/Expenses.java
  backend/src/service/ExpensesService.java
  backend/src/service/ExpensesServiceImpl.java
Labels: 💡feat, 💾server

#123 페이지 css 디테일 수정
  frontend/html/membership.html
  frontend/html/modify.html
  frontend/style/logIn.css
  frontend/style/membership.css
  frontend/style/modify.css
  frontend/style/myPage.css
Labels: 🖥️client, ✒️fix

#124 acoount.js 기능 구현
  frontend/html/account.html
  frontend/js/account.js
  frontend/style/expenseBox.css
Labels: 🖥️client, ✒️fix

#125 fix: account.js 수입지출 데이터 값 삽입 수정
  frontend/js/account.js
Labels: 🖥️client, ✒️fix

#126 expenseAddDiv
  frontend/js/account.js
Labels: 🖥️client, ✒️fix

#128 통계_클래스화_진행_클라이언트_서버연결
  frontend/html/statistics.html
  frontend/js/socket/socket.js
  frontend/js/statistics.js
Labels: 🖥️client, ✒️fix

#129 budget 추가 그래프 위한 추가수정
  backend/src/DAO/BudgetDAO.java
  backend/src/DAO/ExpensesDAO.java
  backend/src/DTO/Budget.java
  backend/src/DTO/Expenses.java
  backend/src/server/Sever.java
  backend/src/service/BudgetService.java
  backend/src/service/BudgetServicelmpl.java
Labels: 💡feat, 💾server, ✒️fix

#130 불필요한 chatSocket 삭제 -> Socket사용,및 디자인 수정
  frontend/js/chat_log.js
  frontend/js/socket/chatSocket.js
  frontend/js/socket/messageHandler.js
  frontend/style/chat_log.css
Labels: 🖥️client, ✒️fix

#131 account.js, css 수정
  frontend/html/account.html
  frontend/js/account.js
  frontend/style/calendar.css
  frontend/style/expenseBox.css
Labels: 🖥️client, ✒️fix

#132 feat: 수입지출내역 추가 및 js, css 추가
  frontend/html/account.html
  frontend/js/account.js
  frontend/style/account.css
Labels: 💡feat, 🖥️client, ✒️fix

#133 css 화면 디테일 수정
  frontend/style/logIn.css
  frontend/style/membership.css
  frontend/style/modify.css
  frontend/style/myPage.css
Labels: 🖥️client, ✒️fix

#134 예산과 지출 제출 버튼 기능 조건 분기
  frontend/html/account.html
  frontend/js/account.js
Labels: 🖥️client, ✒️fix

#135 Fe/fix/grape
  frontend/html/st_grape_income.html
  frontend/js/doughnutGrap.js
  frontend/js/doughnutIncom.js
Labels: 💡feat, 🖥️client, ✒️fix

#136 예산 저장 수정 및 그래프 가져오기위해 수정
  backend/src/DAO/BudgetDAO.java
  backend/src/service/ExpensesServiceImpl.java
Labels: 💡feat, 💾server, ✒️fix

#137 로그인 실패 버그 수정
  README.md
  backend/.classpath
  backend/src/service/UserServiceImpl.java
Labels: 🪳🪲🐞bug, 💾server, ✒️fix

#138 fix: account쪽 errorFixed
  frontend/html/account.html
  frontend/js/account.js
Labels: 🪳🪲🐞bug, 🖥️client, ✒️fix

#139 메시지 핸들러 수정
  frontend/js/socket/messageHandler.js
Labels: 🖥️client, ✒️fix

#140 회원가입 정보 공개여부 버그 수정
  frontend/html/membership.html
  frontend/js/membership.js
Labels: 🪳🪲🐞bug, 🖥️client, ✒️fix

#141 스택그래프 지출 띄우기 시도
  backend/src/DAO/ExpensesDAO.java
  backend/src/service/ExpensesService.java
  backend/src/service/ExpensesServiceImpl.java
Labels: 💡feat, 💾server, ✒️fix

#142 fix: account.js errorFixed
  frontend/js/account.js
  frontend/js/socket/messageHandler.js
  frontend/js/socket/socket.js
Labels: 🪳🪲🐞bug, 🖥️client, ✒️fix

#144 그래프 추출
  frontend/html/st_stac_expend.html
  frontend/js/incomeserver.js
  frontend/js/stacExpenses.js
  frontend/js/stacIncome.js
Labels: 🖥️client, ✒️fix

#146 클라이언트와 서버 연결 및 DAO로 데이터베이스 연결을 확인하기 위한 수정된 코드입니다.
  backend/src/DAO/ExpensesDAO.java
  backend/src/DB/DBConnection.java
  backend/src/server/Sever.java
  backend/src/service/ExpensesService.java
  backend/src/service/ExpensesServiceImpl.java
Labels: 💡feat, 🖥️client, 💾server, ✒️fix

#148 account.html에 채팅창 추가
  frontend/html/account.html
  frontend/js/socket/messageHandler.js
  frontend/style/chat_log.css
Labels: 🖥️client, ✒️fix

#149 fix: client error Fixed
  frontend/html/account.html
  frontend/js/account.js
Labels: 🪳🪲🐞bug, 🖥️client, ✒️fix

#150 fix: error Fixed
  frontend/js/account.js
Labels: 🪳🪲🐞bug, 🖥️client, ✒️fix

#151 fix: errorFixed
  backend/src/DAO/ExpensesDAO.java
  backend/src/service/ExpensesServiceImpl.java
Labels: 🪳🪲🐞bug, 💾server, ✒️fix

#152 chat 버튼 이미지
  frontend/html/account.html
  frontend/images/chat.png
  frontend/style/account.css
  frontend/style/expenseBox.css
Labels: 💡feat, 🖥️client

#154 fix: 수입/지출 내역 조회 에러 수정 및 account.css 수정
  frontend/html/account.html
  frontend/js/account.js
  frontend/js/socket/messageHandler.js
  frontend/style/account.css
Labels: 🪳🪲🐞bug, 🖥️client, ✒️fix

#156 fix: expensesList 조회 error 수정, 필요없는 주석과 출력 삭제
  backend/src/DAO/ExpensesDAO.java
  backend/src/DB/DBConnection.java
  backend/src/server/Sever.java
  backend/src/service/ExpensesService.java
  backend/src/service/ExpensesServiceImpl.java
Labels: 🪳🪲🐞bug, 💾server, ✒️fix

#157 채팅 창 버튼에 오픈, 숨김 이벤트 적용
  frontend/js/chat_log.js
Labels: 💡feat, 🖥️client

#158 필요없는 부분 삭제
  frontend/js/logIn.js
  frontend/js/membership.js
  frontend/js/modify.js
  frontend/js/myPage.js
  frontend/style/logIn.css
  frontend/style/membership.css
  frontend/style/modify.css
  frontend/style/myPage.css
Labels: ❎remove, 🖥️client, ✒️fix

#159 fix: 날짜별 수입 지출 내역 조회 수정 및 중복 메서드 삭제
  frontend/js/account.js
Labels: 🪳🪲🐞bug, 🖥️client, ✒️fix

#160 변경 테마 색상을 localStorage에 저장
  frontend/js/account.js
Labels: 💡feat, 🖥️client

#161 채팅로그가 다른 페이지를 가더라도 유지
  frontend/html/account.html
  frontend/js/chat_log.js
Labels: 💡feat, 🖥️client

#162 fix: deleteBtn 이미지 수정
  frontend/html/account.html
  frontend/images/delete.png
  frontend/js/account.js
  frontend/js/socket/messageHandler.js
  frontend/style/account.css
  frontend/style/expenseBox.css
Labels: 🖥️client, ✒️fix

#163 db 통계 데이터 주고 받기 완성
  backend/src/DAO/ExpensesDAO.java
  backend/src/DB/DBConnection.java
  backend/src/service/ExpensesService.java
  backend/src/service/ExpensesServiceImpl.java
Labels: 💾server, ✒️fix

#164 통계 원형 그래프 완성 / 막대 그래프 미완성
  frontend/html/statistics.html
  frontend/html/statistics_income.html
  frontend/js/socket/socket.js
  frontend/js/statistics.js
  frontend/style/statistics.css
Labels: 🖥️client, ✒️fix

#165 fix: ExpensesDAO에서 getExpensesList 수정
  backend/src/DAO/ExpensesDAO.java
Labels: 💾server, ✒️fix

#166 통계 페이지 심폐소생술
  frontend/html/statistics.html
  frontend/style/statistics.css
Labels: 🖥️client, ✒️fix

#167 localStorage 최종
  frontend/js/statistics.js
  frontend/style/statistics.css
Labels: 🪳🪲🐞bug, 🖥️client, ✒️fix

#168 fix: 가계부 목록 삭제 기능 수정 및 구현 완료
  frontend/js/account.js
  frontend/js/socket/messageHandler.js
Labels: 💡feat, 🖥️client, ✒️fix

#170 메인메뉴 footer / css / 테마 태그/ 막대 그래프 추가
  frontend/html/index.html
  frontend/html/statistics.html
  frontend/html/statistics_income.html
  frontend/js/statistics.js
  frontend/style/main.css
Labels: 💡feat, 🖥️client, ✒️fix

#171 막대 그래프 추가를 위한 쿼리문 추가
  backend/src/DAO/ExpensesDAO.java
  backend/src/DB/DBConnection.java
  backend/src/server/Sever.java
Labels: 💡feat, 💾server, ✒️fix

#172 그래프 css 수정
  frontend/style/header.css
  frontend/style/mark_expend.css
  frontend/style/st_expend.css
  frontend/style/st_income.css
Labels: 🖥️client, ✒️fix

#173 채팅 닉네임 수정
  frontend/js/chat_log.js
Labels: 🖥️client, ✒️fix

#174 통계 사라진 버튼 추가 수입통계 없는 부분 추가
  frontend/html/statistics.html
  frontend/html/statistics_income.html
Labels: 🖥️client, ✒️fix

#175 호스트 주소 수정(서버 컴퓨터로)
  frontend/js/socket/messageHandler.js
Labels: 🖥️client, ✒️fix

#176 DB host ip 정보 수정
  backend/src/DB/DBConnection.java
Labels: 💾server, ✒️fix

#177 login host
  frontend/js/logIn.js
Labels: 🖥️client, ✒️fix

#178 line 정령 수정 및 내 정보, 내 정보 수정에서 account로 넘어가게
  frontend/html/modify.html
  frontend/html/myPage.html
  frontend/style/membership.css
  frontend/style/modify.css
  frontend/style/myPage.css
Labels: 🖥️client, ✒️fix

#179 fix: 필요 없는 파일 삭제, 주석 및 콘솔로그삭제
  frontend/html/account.html
  frontend/html/chat_log.html
  frontend/html/incometotal.html
  frontend/html/index.html
  frontend/html/logIn.html
  frontend/html/membership.html
  frontend/html/modify.html
  frontend/html/month.html
  frontend/html/myPage.html
  frontend/html/st_expend.html
  frontend/html/st_grape_expend.html
  frontend/html/st_grape_income.html
  frontend/html/st_income.html
  frontend/html/st_stac_expend.html
  frontend/html/st_stac_income.html
  frontend/html/statistics.html
  frontend/html/statistics_income.html
  frontend/js/account.js
  frontend/js/chat_log.js
  frontend/js/doughnutGrap.js
  frontend/js/doughnutIncom.js
  frontend/js/expensesServer .js
  frontend/js/incomeserver.js
  frontend/js/logIn.js
  frontend/js/main.js
  frontend/js/membership.js
  frontend/js/modify.js
  frontend/js/socket/messageHandler.js
  frontend/js/socket/socket.js
  frontend/js/st_grape_expend.js
  frontend/js/st_grape_income.js
  frontend/js/st_stac_expend.js
  frontend/js/st_stac_income.js
  frontend/js/stacExpenses.js
  frontend/js/stacIncome.js
  frontend/js/statistics.js
  frontend/js/statisticsServer.js
  frontend/style/calendar.css
  frontend/style/chat_log.css
  frontend/style/expenseBox.css
  frontend/style/graph.css
  frontend/style/logIn.css
  frontend/style/main.css
  frontend/style/membership.css
  frontend/style/modify.css
  frontend/style/myPage.css
  frontend/style/statistics.css
Labels: ❎remove, 🖥️client, ✒️fix

#180 fix: 필요 없는 콘솔, 메소드 삭제
  backend/src/DAO/BudgetDAO.java
  backend/src/DAO/CategoryDAO.java
  backend/src/DAO/ExpensesDAO.java
  backend/src/DB/DBConnection.java
  backend/src/DTO/Budget.java
  backend/src/DTO/Category.java
  backend/src/DTO/Users.java
  backend/src/server/ChatServer.java
  backend/src/server/Sever.java
  backend/src/service/BudgetService.java
  backend/src/service/BudgetServicelmpl.java
  backend/src/service/ExpensesService.java
  backend/src/service/ExpensesServiceImpl.java
  backend/src/service/UserServiceImpl.java
Labels: ❎remove, 💾server, ✒️fix

#181 로그인 후 메인 혹은 통계에서 themore 클릭시 로그인 후 메인으로 이동
  frontend/component/header.html
  frontend/html/statistics_income.html
Labels: 🖥️client, ✒️fix

#182 서버 host 변경
  frontend/js/membership.js
  frontend/js/modify.js
  frontend/js/myPage.js
Labels: 🪳🪲🐞bug, 🖥️client, ✒️fix

#184 statistics host name
  frontend/js/statistics.js
Labels: 🖥️client, ✒️fix

#185 채팅 로그 관련 수정 버그 픽스
  frontend/js/chat_log.js
Labels: 🪳🪲🐞bug, 🖥️client, ✒️fix

#189 fix: 누락된 이미지 재업로드
  frontend/images/3babypig.png
  frontend/images/4960188.png
  frontend/images/Calendar.png
  frontend/images/Pluse.png
  frontend/images/Sign_in_squre.png
  frontend/images/Trending-up.png
  frontend/images/backgroundColor.png
  frontend/images/user_3059416.png
  frontend/images/warning.png
Labels: 🖥️client, ✒️fix

#190 fix: 누락된 quote.css 파일 업로드
  frontend/style/quote.css
Labels: 🪳🪲🐞bug, 🖥️client, ✒️fix
